'use client'

import { useMemo, useState } from 'react'
import { Avatar, AvatarFallback } from '@/components/ui/avatar'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { Input } from '@/components/ui/input'
import { Separator } from '@/components/ui/separator'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Textarea } from '@/components/ui/textarea'
import { Bell, Bookmark, ChevronDown, Compass, Copy, FileText, Flame, Globe2, HelpCircle, ImagePlus, LayoutGrid, Lightbulb, Menu, MessageCircle, MoreHorizontal, Moon, Pin, Plus, Search, Send, Share2, Sparkles, Sun, ThumbsDown, ThumbsUp, TrendingUp, Users, X } from 'lucide-react'

const threads = [
  { id: 1, name: 'Mariana López', initials: 'ML', career: 'TI', time: 'hace 2h', title: '¿Alguien tiene el horario actualizado de laboratorios?', body: 'Estoy armando mi horario para el siguiente cuatrimestre y no encuentro el PDF de laboratorios. ¿Ya lo publicaron en algún grupo?', category: 'Tecnologías de la Información', score: 38, replies: 14, tags: ['#Horarios', '#TI'], color: 'bg-amber-100 text-amber-700' },
  { id: 2, name: 'Diego Ramírez', initials: 'DR', career: 'MEC', time: 'hace 4h', title: 'Tips para conseguir residencia en una startup', body: 'Comparto algunos aprendizajes de mis primeras entrevistas: lleven un proyecto demo, investiguen el stack y pregunten por el plan de acompañamiento. ¿Qué empresas les han funcionado?', category: 'Convocatorias', score: 72, replies: 26, tags: ['#Residencias', '#Consejos'], color: 'bg-sky-100 text-sky-700' },
  { id: 3, name: 'Sofía Hernández', initials: 'SH', career: 'BIO', time: 'ayer', title: 'Material de estudio: bioinformática y Python', body: 'Dejo una pequeña colección de apuntes y ejercicios para quienes están por entrar a la materia. Si ven algún error, avísenme para corregirlo.', category: 'Biotecnología', score: 119, replies: 31, tags: ['#Material', '#Python'], color: 'bg-emerald-100 text-emerald-700' },
]

const categories = ['Tecnologías de la Información', 'Biotecnología', 'Gastronomía', 'Mecatrónica', 'Convocatorias', 'Preguntas Frecuentes']

function Logo() { return <div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-primary text-primary-foreground shadow-sm"><FileText className="size-5" /></div><div><p className="font-bold tracking-tight">Wiki UTOM</p><p className="text-[11px] text-muted-foreground">Comunidad estudiantil</p></div></div> }

function ThreadCard({ thread }: { thread: typeof threads[number] }) {
  const [score, setScore] = useState(thread.score)
  const [vote, setVote] = useState<'up' | 'down' | null>(null)
  const [expanded, setExpanded] = useState(false)
  const [saved, setSaved] = useState(false)
  return <Card className="overflow-hidden border-border/70 shadow-sm transition-shadow hover:shadow-md">
    <CardContent className="p-5">
      <div className="flex items-start gap-3"><Avatar className="size-10"><AvatarFallback className="bg-secondary text-xs font-semibold">{thread.initials}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="text-sm font-semibold">{thread.name}</p><Badge variant="secondary" className="rounded-md px-1.5 py-0 text-[10px]">{thread.career}</Badge><span className="text-xs text-muted-foreground">· {thread.time}</span></div><p className="mt-0.5 text-xs text-muted-foreground">Estudiante UTOM</p></div><DropdownMenu><DropdownMenuTrigger><Button variant="ghost" size="icon" className="size-8"><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => setSaved(!saved)}>{saved ? 'Quitar guardado' : 'Guardar hilo'}</DropdownMenuItem><DropdownMenuItem>Reportar publicación</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>
      <div className="mt-4"><div className="mb-2 flex flex-wrap items-center gap-2"><Badge className={`${thread.color} border-0 text-[11px]`} variant="outline">{thread.category}</Badge>{thread.tags.map(tag => <span key={tag} className="text-xs text-muted-foreground">{tag}</span>)}</div><h3 className="text-[17px] font-bold leading-snug tracking-tight">{thread.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{thread.body}</p></div>
      <div className="mt-5 flex items-center gap-1"><div className="flex items-center rounded-lg border border-border/70"><Button variant="ghost" size="sm" className={`h-8 rounded-r-none px-2.5 ${vote === 'up' ? 'text-primary' : ''}`} onClick={() => { setVote(vote === 'up' ? null : 'up'); setScore(score + (vote === 'up' ? -1 : vote === 'down' ? 2 : 1)) }}><ThumbsUp className="mr-1.5 size-3.5" />{score}</Button><Separator orientation="vertical" className="h-4" /><Button variant="ghost" size="sm" className={`h-8 rounded-l-none px-2.5 ${vote === 'down' ? 'text-destructive' : ''}`} onClick={() => { setVote(vote === 'down' ? null : 'down'); setScore(score + (vote === 'down' ? 1 : vote === 'up' ? -2 : -1)) }}><ThumbsDown className="size-3.5" /></Button></div><Button variant="ghost" size="sm" className="h-8 gap-1.5 text-xs text-muted-foreground" onClick={() => setExpanded(!expanded)}><MessageCircle className="size-3.5" />{thread.replies} respuestas</Button><Button variant="ghost" size="icon" className={`size-8 ${saved ? 'text-primary' : 'text-muted-foreground'}`} onClick={() => setSaved(!saved)}><Bookmark className="size-4" fill={saved ? 'currentColor' : 'none'} /></Button><Button variant="ghost" size="icon" className="size-8 text-muted-foreground"><Share2 className="size-4" /></Button></div>
      {expanded && <div className="mt-4 border-t pt-4"><div className="flex gap-3"><Avatar className="size-8"><AvatarFallback className="text-[10px]">JR</AvatarFallback></Avatar><div className="flex-1 rounded-xl bg-muted/70 px-3 py-2"><p className="text-xs font-semibold">Jorge Ruiz <span className="ml-1 font-normal text-muted-foreground">hace 1h</span></p><p className="mt-1 text-sm text-muted-foreground">También me interesa, ¿saben si ya habilitaron el sistema?</p></div></div><div className="ml-11 mt-3 flex gap-3 border-l pl-4"><Avatar className="size-7"><AvatarFallback className="text-[10px]">AP</AvatarFallback></Avatar><div><p className="text-xs font-semibold">Ana Pérez <span className="ml-1 font-normal text-muted-foreground">hace 42 min</span></p><p className="mt-1 text-sm text-muted-foreground">Sí, lo vi en Control Escolar esta mañana.</p></div></div><div className="mt-4 flex gap-2"><Input placeholder="Responder a este comentario..." className="h-9 bg-background text-xs" /><Button size="icon" className="size-9"><Send /></Button></div></div>}
    </CardContent>
  </Card>
}

export default function WikiForum() {
  const [query, setQuery] = useState('')
  const [activeTab, setActiveTab] = useState('para-ti')
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null)
  const [dark, setDark] = useState(false)
  const filteredThreads = useMemo(() => threads.filter(t => (!selectedCategory || t.category === selectedCategory) && (!query || `${t.title} ${t.body} ${t.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()))), [query, selectedCategory])
  return <div className={dark ? 'dark min-h-screen bg-background' : 'min-h-screen bg-background'}>
    <header className="sticky top-0 z-20 border-b bg-background/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-[1440px] items-center gap-4 px-4 lg:px-8"><Button variant="ghost" size="icon" className="lg:hidden"><Menu /></Button><Logo /><div className="hidden min-w-0 flex-1 max-w-md md:block"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar en hilos, materias, avisos..." className="h-9 bg-muted/50 pl-9 pr-16 text-sm" /><kbd className="absolute right-2 top-1.5 hidden rounded border bg-background px-1.5 py-1 text-[10px] text-muted-foreground lg:block">⌘ K</kbd></div></div><nav className="ml-auto hidden items-center gap-1 lg:flex"><Button variant="ghost" size="sm">Feed</Button><Button variant="ghost" size="sm">Carreras</Button><Button variant="ghost" size="sm">Avisos oficiales</Button></nav><div className="ml-auto flex items-center gap-1 lg:ml-3"><Button variant="ghost" size="icon" onClick={() => setDark(!dark)} aria-label="Cambiar tema">{dark ? <Sun /> : <Moon />}</Button><Button variant="ghost" size="icon" className="relative"><Bell /><span className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-primary" /></Button><CreateThread /><DropdownMenu><DropdownMenuTrigger><Button variant="ghost" className="ml-1 gap-2 px-1.5"><Avatar className="size-8"><AvatarFallback className="bg-primary text-xs text-primary-foreground">LM</AvatarFallback></Avatar><ChevronDown className="hidden size-3.5 text-muted-foreground sm:block" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem>Mi perfil · TI 5to</DropdownMenuItem><DropdownMenuItem>Mis guardados</DropdownMenuItem><DropdownMenuItem>Cerrar sesión</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></div></header>
    <div className="mx-auto grid max-w-[1440px] grid-cols-1 gap-6 px-4 py-6 lg:grid-cols-[220px_minmax(0,1fr)_280px] lg:px-8"><aside className="hidden lg:block"><div className="sticky top-24"><p className="mb-3 px-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Explorar</p><div className="flex flex-col gap-1">{categories.map((category, i) => <button key={category} onClick={() => setSelectedCategory(selectedCategory === category ? null : category)} className={`flex items-center gap-3 rounded-lg px-3 py-2 text-left text-sm transition-colors ${selectedCategory === category ? 'bg-primary/10 font-medium text-primary' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><span className={`size-2 rounded-full ${i === 0 ? 'bg-primary' : i === 1 ? 'bg-emerald-500' : i === 2 ? 'bg-orange-400' : i === 3 ? 'bg-blue-400' : 'bg-muted-foreground/40'}`} />{category}</button>)}</div><Separator className="my-5" /><p className="mb-3 px-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Atajos</p><div className="flex flex-col gap-1"><Button variant="ghost" className="justify-start gap-3 text-muted-foreground"><Bookmark />Mis guardados</Button><Button variant="ghost" className="justify-start gap-3 text-muted-foreground"><Flame />Hilos populares</Button><Button variant="ghost" className="justify-start gap-3 text-muted-foreground"><Users />Comunidad</Button></div><p className="mt-10 px-3 text-xs leading-5 text-muted-foreground">Wiki UTOM · 2025<br />Hecho por estudiantes, para estudiantes.</p></div></aside>
      <main className="min-w-0"><div className="mb-6"><div className="flex items-end justify-between"><div><p className="text-sm font-medium text-primary">Miércoles, 25 de septiembre</p><h1 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">Tu comunidad, al día.</h1></div><Button variant="outline" size="sm" className="hidden gap-2 sm:flex"><Compass />Explorar</Button></div></div><div className="mb-4 rounded-xl border bg-card p-3 shadow-sm"><div className="flex items-center gap-3"><Avatar className="size-9"><AvatarFallback className="bg-primary/10 text-primary">LM</AvatarFallback></Avatar><button className="flex h-9 flex-1 items-center rounded-lg bg-muted/60 px-3 text-left text-sm text-muted-foreground hover:bg-muted">¿Qué quieres compartir con la comunidad?</button><Button size="icon" variant="ghost" className="hidden sm:flex"><ImagePlus /></Button></div></div><Tabs value={activeTab} onValueChange={setActiveTab} className="mb-5"><TabsList className="h-10 w-full justify-start overflow-x-auto bg-transparent p-0"><TabsTrigger value="para-ti" className="h-10 rounded-none border-b-2 border-transparent px-3 text-xs data-[state=active]:border-primary data-[state=active]:bg-transparent data-[state=active]:text-primary sm:text-sm">Para ti</TabsTrigger><TabsTrigger value="recientes" className="h-10 rounded-none border-b-2 border-transparent px-3 text-xs data-[state=active]:border-primary data-[state=active]:bg-transparent data-[state=active]:text-primary sm:text-sm">Más recientes</TabsTrigger><TabsTrigger value="tendencia" className="h-10 rounded-none border-b-2 border-transparent px-3 text-xs data-[state=active]:border-primary data-[state=active]:bg-transparent data-[state=active]:text-primary sm:text-sm">En tendencia</TabsTrigger><TabsTrigger value="avisos" className="h-10 rounded-none border-b-2 border-transparent px-3 text-xs data-[state=active]:border-primary data-[state=active]:bg-transparent data-[state=active]:text-primary sm:text-sm">Avisos del campus</TabsTrigger></TabsList></Tabs><div className="flex flex-col gap-4">{filteredThreads.map(thread => <ThreadCard key={thread.id} thread={thread} />)}{!filteredThreads.length && <Card><CardContent className="flex flex-col items-center gap-2 py-12 text-center"><Search className="size-8 text-muted-foreground" /><p className="font-medium">No encontramos hilos</p><p className="text-sm text-muted-foreground">Prueba con otra búsqueda o categoría.</p></CardContent></Card>}</div></main>
      <aside className="hidden xl:block"><div className="sticky top-24 flex flex-col gap-4"><Card className="border-primary/20 bg-primary/[0.03]"><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-sm"><Pin className="size-4 text-primary" />Avisos importantes</CardTitle></CardHeader><CardContent className="flex flex-col gap-4 pt-0"><div><Badge variant="outline" className="mb-1 border-primary/30 text-[10px] text-primary">OFICIAL</Badge><p className="text-sm font-medium">Inscripciones al próximo cuatrimestre</p><p className="mt-1 text-xs text-muted-foreground">Del 30 de septiembre al 4 de octubre.</p></div><Separator /><div><Badge variant="outline" className="mb-1 text-[10px]">EVENTO</Badge><p className="text-sm font-medium">Feria de clubes UTOM</p><p className="mt-1 text-xs text-muted-foreground">Conoce las actividades este viernes.</p></div></CardContent></Card><Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-sm"><TrendingUp className="size-4 text-primary" />Temas populares</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2 pt-0">{['#Inscripciones', '#Residencias', '#Hackathon', '#Cafetería', '#ServicioSocial'].map(tag => <Badge key={tag} variant="secondary" className="rounded-md font-normal">{tag}</Badge>)}</CardContent></Card><Card className="bg-muted/40"><CardContent className="p-4"><div className="flex items-start gap-3"><div className="grid size-8 shrink-0 place-items-center rounded-lg bg-background"><Lightbulb className="size-4 text-primary" /></div><div><p className="text-sm font-semibold">Cuidemos la comunidad</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Comparte con respeto, verifica la información y ayuda a tus compañeros.</p><Button variant="link" className="h-auto p-0 pt-2 text-xs">Ver guía de convivencia</Button></div></div></CardContent></Card></div></aside>
    </div>
  </div>
}

function CreateThread() { const [open, setOpen] = useState(false); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger><Button size="sm" className="hidden gap-2 sm:flex"><Plus />Crear hilo</Button></DialogTrigger><DialogContent className="sm:max-w-[560px]"><DialogHeader><DialogTitle>Crear nuevo hilo</DialogTitle><DialogDescription>Comparte una duda, recurso o aviso con tu comunidad.</DialogDescription></DialogHeader><div className="flex flex-col gap-4 py-2"><div className="flex flex-col gap-2"><label htmlFor="title" className="text-sm font-medium">Título</label><Input id="title" placeholder="¿De qué quieres hablar?" /></div><div className="grid gap-4 sm:grid-cols-2"><div className="flex flex-col gap-2"><label htmlFor="category" className="text-sm font-medium">Categoría</label><select id="category" className="h-9 rounded-md border bg-background px-3 text-sm"><option>Tecnologías de la Información</option><option>Biotecnología</option><option>Convocatorias</option><option>Preguntas Frecuentes</option></select></div><div className="flex flex-col gap-2"><label htmlFor="tags" className="text-sm font-medium">Etiquetas</label><Input id="tags" placeholder="#ejemplo, #campus" /></div></div><div className="flex flex-col gap-2"><label htmlFor="body" className="text-sm font-medium">Contenido</label><Textarea id="body" placeholder="Escribe tu publicación..." className="min-h-28 resize-none" /></div><div className="flex cursor-pointer items-center gap-3 rounded-lg border border-dashed p-4 text-sm text-muted-foreground hover:bg-muted/50"><ImagePlus className="size-5" /><span>Adjuntar una imagen o archivo</span></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancelar</Button><Button onClick={() => setOpen(false)}>Publicar hilo</Button></DialogFooter></DialogContent></Dialog> }

export { Copy, Globe2, HelpCircle, LayoutGrid, Sparkles, X }
